### ISSUE TITLE
java.lang.NoSuchMethodError: No static method encPath 

### ISSUE THREAD

**Issue by jsalatiel** [moberwasserlechner/jopencage#29]
I am trying to use your library on android but i always get a crash with:

```
    java.lang.NoSuchMethodError: No static method encPath(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Lorg/apache/http/client/utils/URLEncodedUtils; or its super classes (declaration of 'org.apache.http.client.utils.URLEncodedUtils' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at org.apache.http.client.utils.URIBuilder.encodePath(URIBuilder.java:191)
        at org.apache.http.client.utils.URIBuilder.buildString(URIBuilder.java:152)
        at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:120)
        at com.byteowls.jopencage.JOpenCageGeocoder.buildUri(JOpenCageGeocoder.java:71)
        at com.byteowls.jopencage.JOpenCageGeocoder.sendRequest(JOpenCageGeocoder.java:77)
        at com.byteowls.jopencage.JOpenCageGeocoder.reverse(JOpenCageGeocoder.java:52)
```

**Comment by moberwasserlechner** [comment]
This lib does not support the usage with Android. But looking at your error  Android has a Problem with Apache httpClient, which this lib uses.
