### ISSUE TITLE
no encPath method in class URLEncodedUtils

### ISSUE THREAD

**Issue by xcharxlie** [moberwasserlechner/jopencage#42]
Hi there,

I'm now using JOpenCage to do my project in an Android  App. However I got a complaint as following while it's calling jOpenCageGeocoder.forward() : 

    Caused by: java.lang.NoSuchMethodError: No static method encPath(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Lorg/apache/http/client/utils/URLEncodedUtils; or its super classes (declaration of 'org.apache.http.client.utils.URLEncodedUtils' appears in /system/framework/org.apache.http.legacy.jar)
            at org.apache.http.client.utils.URIBuilder.encodePath(URIBuilder.java:210)
            at org.apache.http.client.utils.URIBuilder.buildString(URIBuilder.java:151)
            at org.apache.http.client.utils.URIBuilder.build(URIBuilder.java:119)
            at com.byteowls.jopencage.JOpenCageGeocoder.buildUri(JOpenCageGeocoder.java:71)
            at com.byteowls.jopencage.JOpenCageGeocoder.sendRequest(JOpenCageGeocoder.java:77)
            at com.byteowls.jopencage.JOpenCageGeocoder.forward(JOpenCageGeocoder.java:48)
            at com.example.ee497app.Telenav.location(Telenav.java:392)
            at com.example.ee497app.Telenav.testAddress(Telenav.java:335)
            at com.example.ee497app.Telenav.testApp(Telenav.java:267)
            at com.example.ee497app.MainActivity.sendMassage(MainActivity.java:99)

It seems like something goes wrong with the deprecated API. This is my build.gradle using SDK30.

    android {
        compileSdkVersion 30
        buildToolsVersion "30.0.3"
        useLibrary  'org.apache.http.legacy'

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module")
    }
    defaultConfig {
        applicationId "com.example.ee497app"
        minSdkVersion 16
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    dependencies {
        implementation 'androidx.core:core:1.3.0'
        implementation 'androidx.appcompat:appcompat:1.1.0'
        implementation 'com.google.android.material:material:1.1.0'
        implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
        testImplementation 'junit:junit:4.+'
        androidTestImplementation 'androidx.test.ext:junit:1.1.1'
        androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
        implementation "org.slf4j:slf4j-api:${slf4jVersion}"
        implementation "org.apache.httpcomponents:httpclient:${httpClientVersion}"
        implementation group: 'cz.msebera.android' , name: 'httpclient', version: '4.4.1.1'
        implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
        implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
        implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    }
}

I got a warning that httpclient conflicts with classes provided now by Android at the line:  implementation "org.apache.httpcomponents:httpclient:${httpClientVersion}" 
Could anyone help to resolve this problem? Thanks in advance.

**Comment by moberwasserlechner** [comment]
I know it does not help you but this lib was not created with Android in mind.

That said one bit of config catches my sight:

```
    implementation "org.apache.httpcomponents:httpclient:${httpClientVersion}"
    implementation group: 'cz.msebera.android' , name: 'httpclient', version: '4.4.1.1'
```

Are you sure those 2 dependencies did not cause the confict?

**Comment by moberwasserlechner** [comment]
No answer in 2 month. So I'm closing this.
